version: 2
updates:
  - package-ecosystem: "composer"
  directory: "/"
  schedule:
    interval: "daily"
  assignees:
    - "Coho04"
  reviewers:
    - "Coho04"

- package-ecosystem: "package"
  directory: "/"
  schedule:
    interval: "daily"
  assignees:
    - "Coho04"
  reviewers:
    - "Coho04"

